baseURL = "https://gary-yao.com/"
languageCode = "en-us"
title = "Gary Yao"

[params]
  description = "Personal blog of Gary Yao"
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Photos"
    url = "/photos/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
  [[menu.main]]
    name = "Archive"
    url = "/archive/"
    weight = 5 